apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-nodejs
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/anaisurlichs/knative-nodejs:1.0.0
          env:
            - name: TARGET
              value: "Node.js Sample v1"